#!/bin/bash
ARGUMENT=$1;
if [[ -f $ARGUMENT ]]; then
    # GET HERE IF FILE ARGUMENT IS VALID:
    # USE sed MAGIC TO DO THE WORK:
    # HERE WE ADD uFEFF BYTE ORDER MARK AS 
    # INDIVIDUAL UTF-8 BYTES:
    #sed -i .bak '1s/^/\xef\xbb\xbf/' $ARGUMENT
    sed -E -i.bak '1s/^/﻿/' $ARGUMENT
else
    echo "ADDBOM is (c) 2019 by Edward H. Trager."
    echo ""
    echo "addbom adds a Unicode byte order mark to the beginning of a file."
    echo "Microsoft Excel very curiously requires this in order to treat a file as UTF-8."
    echo ""
    echo "Please pass a valid file name as the command line argument."
    exit 1
fi
